CREATE DATABASE PUBLICINSTITUTIONCHAT;

USE PUBLICINSTITUTIONCHAT;

CREATE TABLE INSTITUTIONS( id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, geolatitude FLOAT(15) NOT NULL, geolongitude FLOAT(15) NOT NULL, PRIMARY KEY ( id ) );

CREATE TABLE CHANNELS( id INT NOT NULL AUTO_INCREMENT, institution_id INT NOT NULL, name VARCHAR(30) NOT NULL, PRIMARY KEY ( id ), FOREIGN KEY (institution_id) REFERENCES INSTITUTIONS(id) ON DELETE CASCADE);
